In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.preprocessing as spre

# Standard

In [2]:
a1 = np.array([-70,-100,0,100,200.0]).reshape(-1,1)


In [3]:
s = spre.StandardScaler()
#s = spre.StandardScaler(with_mean=True,with_std=False)

In [4]:
s.fit(a1)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
s.transform(a1)

array([[-0.86546214],
       [-1.13591905],
       [-0.23439599],
       [ 0.66712706],
       [ 1.56865012]])

In [6]:
s.fit_transform(a1)

array([[-0.86546214],
       [-1.13591905],
       [-0.23439599],
       [ 0.66712706],
       [ 1.56865012]])

# minmax

In [7]:
a1 = np.array([30.0,40,70,120]).reshape(-1,1)
s = spre.MinMaxScaler()

In [14]:
a2 = s.fit_transform(a1)

In [15]:
a2

array([[0.        ],
       [0.11111111],
       [0.44444444],
       [1.        ]])

In [16]:
s = spre.MinMaxScaler((30,120))

In [17]:
s.fit_transform(a2)

array([[ 30.],
       [ 40.],
       [ 70.],
       [120.]])

# Robust

In [27]:
s = spre.RobustScaler()

In [7]:
s.fit_transform(a1)

array([[-0.41176471],
       [-0.58823529],
       [ 0.        ],
       [ 0.58823529],
       [ 1.17647059]])

In [19]:
Q1 = np.percentile(a1,25)
Q1

-70.0

In [20]:
Q2 =np.percentile(a1,50)
Q2

0.0

In [21]:
Q3 = np.percentile(a1,75)
Q3

100.0

In [11]:
for i in range(len(a1)):
    a1[i,0]= ((a1[i,0] - Q2) / (Q3 - Q1))


In [12]:
a1

array([[-0.41176471],
       [-0.58823529],
       [ 0.        ],
       [ 0.58823529],
       [ 1.17647059]])