In [1]:
import numpy as np

In [2]:
import sklearn.metrics as skmet

In [7]:
tr   = np.array([0,0,0,0,0,0,0,0,1,1,1,1,1,1])
pred = np.array([0,0,1,1,1,0,0,0,1,1,0,0,1,1])

In [8]:
skmet.confusion_matrix(tr,pred)

array([[5, 3],
       [2, 4]], dtype=int64)

# TN       FP
# FN       TP

In [12]:
tr   = np.array([0,0,0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2])
pred = np.array([0,0,1,1,1,0,0,0,1,1,0,0,1,1,1,1,2,1,1])

In [13]:
skmet.confusion_matrix(tr,pred)

array([[5, 3, 0],
       [2, 4, 0],
       [0, 4, 1]], dtype=int64)

In [14]:
tr   = np.array([0,0,0,0,0,0,0,0,1,1,1,1,1,1])
pred = np.array([0,0,1,1,1,0,0,0,1,1,0,0,1,1])
print(skmet.classification_report(tr,pred))

              precision    recall  f1-score   support

           0       0.71      0.62      0.67         8
           1       0.57      0.67      0.62         6

    accuracy                           0.64        14
   macro avg       0.64      0.65      0.64        14
weighted avg       0.65      0.64      0.64        14



In [15]:
skmet.precision_score(tr,pred,pos_label=0)

0.7142857142857143

In [16]:
tr   = np.array([0,0,0,0,0,0,0,0,1,1,1,1,1,1])
pred = np.array([0,0,0,0,0,0,0,0,1,1,0,0,1,1])
print(skmet.classification_report(tr,pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       1.00      0.67      0.80         6

    accuracy                           0.86        14
   macro avg       0.90      0.83      0.84        14
weighted avg       0.89      0.86      0.85        14



In [17]:
skmet.confusion_matrix(tr,pred)

array([[8, 0],
       [2, 4]], dtype=int64)

### f1_score = 2 * ((pre * recall)/(pre + recall))

In [18]:
tr   = np.array([0,0,0,0,0,0,0,0,1,1,1,1,1,1])
pred = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0])
print(skmet.classification_report(tr,pred))

              precision    recall  f1-score   support

           0       0.57      1.00      0.73         8
           1       0.00      0.00      0.00         6

    accuracy                           0.57        14
   macro avg       0.29      0.50      0.36        14
weighted avg       0.33      0.57      0.42        14



C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
skmet.confusion_matrix(tr,pred)

array([[8, 0],
       [6, 0]], dtype=int64)