In [34]:
import numpy as np
import pandas as pd
import seaborn as sb

In [35]:
df = pd.read_csv("simp.csv")

In [36]:
df.head()

A  B  C  RESULT
0  0  1  0       1
1  1  0  0       0
2  0  0  0       1
3  0  0  1       1
4  0  0  0       0

In [37]:
df.shape

(300, 4)

In [38]:
import sklearn.linear_model as sklin

In [39]:
model = sklin.LogisticRegression()

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('RESULT',axis=1), df['RESULT'], test_size=0.33, random_state=42)

In [42]:
model.fit(X_train,y_train)

LogisticRegression()

In [43]:
pred = model.predict(X_test)

In [11]:
pred

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

In [12]:
y_test

203    0
266    1
152    0
9      1
233    0
      ..
37     0
16     0
179    1
147    0
274    0
Name: RESULT, Length: 99, dtype: int64

In [13]:
np.mean(pred != y_test)

0.020202020202020204

In [14]:
import sklearn.metrics as skmet

In [15]:
skmet.confusion_matrix(y_test,pred)
# 

array([[43,  0],
       [ 2, 54]], dtype=int64)

In [16]:
print(skmet.classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        43
           1       1.00      0.96      0.98        56

    accuracy                           0.98        99
   macro avg       0.98      0.98      0.98        99
weighted avg       0.98      0.98      0.98        99



In [20]:
model.coef_

array([[0.33449841, 3.51021748, 4.68248909]])

In [19]:
model.intercept_

array([-1.96742267])

In [22]:
import math
def predict(a,b,c):
    return 1 / (1 + math.exp(-1*(0.33449841*a + 3.51021748*b + 4.68248909*c -1.967)))

In [23]:
pred

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

In [24]:
X_test.head(5)

A  B  C
203  0  0  0
266  0  0  1
152  0  0  0
9    0  1  1
233  0  0  0

In [33]:
print(predict(0,0,0))
print(predict(0,0,1))
print(predict(0,1,1))

0.12271148156880178
0.9379344564483476
0.9980259786891493


In [27]:
model.predict_proba

<bound method LogisticRegression.predict_proba of LogisticRegression()>

In [32]:
model.predict_proba(np.array([0,0,0]).reshape(1,-1))

array([[0.87733401, 0.12266599]])